Traceback (most recent call last):
  File "C:\Users\Fujitsu\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_core\utils\__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Fujitsu\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Fujitsu\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Fujitsu\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_core\utils\__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Fujitsu\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Fujitsu\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Fujitsu\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Fujitsu\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
network = LSTMFCNClassifier(n_epochs=65, verbose=0)
network.fit(X_train, y_train)
network.score(X_test, y_test)
------------------


[31m---------------------------------------------------------------------------[39m
[31mModuleNotFoundError[39m                       Traceback (most recent call last)
[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\sktime\utils\validation\_dependencies.py:138[39m, in [36m_check_soft_dependencies[39m[34m(package_import_alias, severity, obj, msg, suppress_import_stdout, *packages)[39m
[32m    137[39m     [38;5;28;01melse[39;00m:
[32m--> [39m[32m138[39m         pkg_ref = [43mimport_module[49m[43m([49m[43mpackage_import_name[49m[43m)[49m
[32m    139[39m [38;5;66;03m# if package cannot be imported, make the user aware of installation requirement[39;00m

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py:90[39m, in [36mimport_module[39m[34m(name, package)[39m
[32m     89[39m         level += [32m1[39m
[32m---> [39m[32m90[39m [38;5;28;01mreturn[39;00m [43m_bootstrap[49m[43m.[49m[43m_gcd_import[49m[43m([49m[43mname[49m[43m[[49m[43mlevel[49m[43m:[49m[43m][49m[43m,[49m[43m [49m[43mpackage[49m[43m,[49m[43m [49m[43mlevel[49m[43m)[49m

[36mFile [39m[32m<frozen importlib._bootstrap>:1387[39m, in [36m_gcd_import[39m[34m(name, package, level)[39m

[36mFile [39m[32m<frozen importlib._bootstrap>:1360[39m, in [36m_find_and_load[39m[34m(name, import_)[39m

[36mFile [39m[32m<frozen importlib._bootstrap>:1324[39m, in [36m_find_and_load_unlocked[39m[34m(name, import_)[39m

[31mModuleNotFoundError[39m: No module named 'tensorflow'

The above exception was the direct cause of the following exception:

[31mModuleNotFoundError[39m                       Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[4][39m[32m, line 1[39m
[32m----> [39m[32m1[39m network = [43mLSTMFCNClassifier[49m[43m([49m[43mn_epochs[49m[43m=[49m[32;43m65[39;49m[43m,[49m[43m [49m[43mverbose[49m[43m=[49m[32;43m0[39;49m[43m)[49m
[32m      2[39m network.fit(X_train, y_train)
[32m      3[39m network.score(X_test, y_test)

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\sktime\classification\deep_learning\lstmfcn.py:79[39m, in [36mLSTMFCNClassifier.__init__[39m[34m(self, n_epochs, batch_size, dropout, kernel_sizes, filter_sizes, lstm_size, attention, callbacks, random_state, verbose)[39m
[32m     66[39m [38;5;28;01mdef[39;00m[38;5;250m [39m[34m__init__[39m(
[32m     67[39m     [38;5;28mself[39m,
[32m     68[39m     n_epochs=[32m2000[39m,
[32m   (...)[39m[32m     77[39m     verbose=[32m0[39m,
[32m     78[39m ):
[32m---> [39m[32m79[39m     [38;5;28;43msuper[39;49m[43m([49m[43m)[49m[43m.[49m[34;43m__init__[39;49m[43m([49m[43m)[49m
[32m     81[39m     [38;5;28mself[39m.classes_ = [38;5;28;01mNone[39;00m
[32m     82[39m     [38;5;28mself[39m.input_shape = [38;5;28;01mNone[39;00m

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\sktime\classification\deep_learning\base.py:44[39m, in [36mBaseDeepClassifier.__init__[39m[34m(self, batch_size, random_state)[39m
[32m     43[39m [38;5;28;01mdef[39;00m[38;5;250m [39m[34m__init__[39m([38;5;28mself[39m, batch_size=[32m40[39m, random_state=[38;5;28;01mNone[39;00m):
[32m---> [39m[32m44[39m     [38;5;28;43msuper[39;49m[43m([49m[43m)[49m[43m.[49m[34;43m__init__[39;49m[43m([49m[43m)[49m
[32m     46[39m     [38;5;28mself[39m.batch_size = batch_size
[32m     47[39m     [38;5;28mself[39m.random_state = random_state

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\sktime\classification\base.py:104[39m, in [36mBaseClassifier.__init__[39m[34m(self)[39m
[32m    101[39m [38;5;28mself[39m._converter_store_y = {}
[32m    103[39m [38;5;28msuper[39m().[34m__init__[39m()
[32m--> [39m[32m104[39m [43m_check_estimator_deps[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\sktime\utils\validation\_dependencies.py:433[39m, in [36m_check_estimator_deps[39m[34m(obj, msg, severity)[39m
[32m    431[39m     pkg_deps = [pkg_deps]
[32m    432[39m [38;5;28;01mif[39;00m pkg_deps [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[32m--> [39m[32m433[39m     pkg_deps_ok = [43m_check_soft_dependencies[49m[43m([49m
[32m    434[39m [43m        [49m[43m*[49m[43mpkg_deps[49m[43m,[49m[43m [49m[43mseverity[49m[43m=[49m[43mseverity[49m[43m,[49m[43m [49m[43mobj[49m[43m=[49m[43mobj[49m[43m,[49m[43m [49m[43mpackage_import_alias[49m[43m=[49m[43mpck_alias[49m
[32m    435[39m [43m    [49m[43m)[49m
[32m    436[39m     compatible = compatible [38;5;129;01mand[39;00m pkg_deps_ok
[32m    438[39m [38;5;28;01mreturn[39;00m compatible

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\sktime\utils\validation\_dependencies.py:163[39m, in [36m_check_soft_dependencies[39m[34m(package_import_alias, severity, obj, msg, suppress_import_stdout, *packages)[39m
[32m    159[39m [38;5;66;03m# if msg is not None, none of the above is executed,[39;00m
[32m    160[39m [38;5;66;03m# so if msg is passed it overrides the default messages[39;00m
[32m    162[39m [38;5;28;01mif[39;00m severity == [33m"[39m[33merror[39m[33m"[39m:
[32m--> [39m[32m163[39m     [38;5;28;01mraise[39;00m [38;5;167;01mModuleNotFoundError[39;00m(msg) [38;5;28;01mfrom[39;00m[38;5;250m [39m[34;01me[39;00m
[32m    164[39m [38;5;28;01melif[39;00m severity == [33m"[39m[33mwarning[39m[33m"[39m:
[32m    165[39m     warnings.warn(msg, stacklevel=[32m2[39m)

[31mModuleNotFoundError[39m: LSTMFCNClassifier requires package 'tensorflow' to be present in the python environment, but 'tensorflow' was not found. 'tensorflow' is a soft dependency and not included in the base sktime installation. Please run: `pip install tensorflow` to install the tensorflow package. To install all soft dependencies, run: `pip install sktime[all_extras]`

