Traceback (most recent call last):
  File "C:\Users\Fujitsu\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_core\utils\__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Fujitsu\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Fujitsu\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Fujitsu\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_core\utils\__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Fujitsu\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Fujitsu\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Fujitsu\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Fujitsu\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
benchmark = ForecastingBenchmark()
------------------


[31m---------------------------------------------------------------------------[39m
[31mModuleNotFoundError[39m                       Traceback (most recent call last)
[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\sktime\utils\validation\_dependencies.py:138[39m, in [36m_check_soft_dependencies[39m[34m(package_import_alias, severity, obj, msg, suppress_import_stdout, *packages)[39m
[32m    137[39m     [38;5;28;01melse[39;00m:
[32m--> [39m[32m138[39m         pkg_ref = [43mimport_module[49m[43m([49m[43mpackage_import_name[49m[43m)[49m
[32m    139[39m [38;5;66;03m# if package cannot be imported, make the user aware of installation requirement[39;00m

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py:90[39m, in [36mimport_module[39m[34m(name, package)[39m
[32m     89[39m         level += [32m1[39m
[32m---> [39m[32m90[39m [38;5;28;01mreturn[39;00m [43m_bootstrap[49m[43m.[49m[43m_gcd_import[49m[43m([49m[43mname[49m[43m[[49m[43mlevel[49m[43m:[49m[43m][49m[43m,[49m[43m [49m[43mpackage[49m[43m,[49m[43m [49m[43mlevel[49m[43m)[49m

[36mFile [39m[32m<frozen importlib._bootstrap>:1387[39m, in [36m_gcd_import[39m[34m(name, package, level)[39m

[36mFile [39m[32m<frozen importlib._bootstrap>:1360[39m, in [36m_find_and_load[39m[34m(name, import_)[39m

[36mFile [39m[32m<frozen importlib._bootstrap>:1324[39m, in [36m_find_and_load_unlocked[39m[34m(name, import_)[39m

[31mModuleNotFoundError[39m: No module named 'kotsu'

The above exception was the direct cause of the following exception:

[31mModuleNotFoundError[39m                       Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[2][39m[32m, line 1[39m
[32m----> [39m[32m1[39m benchmark = [43mForecastingBenchmark[49m[43m([49m[43m)[49m

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\sktime\benchmarking\forecasting.py:77[39m, in [36mForecastingBenchmark.__init__[39m[34m(self, id_format)[39m
[32m     76[39m [38;5;28;01mdef[39;00m[38;5;250m [39m[34m__init__[39m([38;5;28mself[39m, id_format: Optional[[38;5;28mstr[39m] = [38;5;28;01mNone[39;00m):
[32m---> [39m[32m77[39m     [38;5;28;43msuper[39;49m[43m([49m[43m)[49m[43m.[49m[34;43m__init__[39;49m[43m([49m[43mid_format[49m[43m)[49m

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\sktime\benchmarking\benchmarks.py:85[39m, in [36mBaseBenchmark.__init__[39m[34m(self, id_format)[39m
[32m     84[39m [38;5;28;01mdef[39;00m[38;5;250m [39m[34m__init__[39m([38;5;28mself[39m, id_format: Optional[[38;5;28mstr[39m] = [38;5;28;01mNone[39;00m):
[32m---> [39m[32m85[39m     [43m_check_soft_dependencies[49m[43m([49m[33;43m"[39;49m[33;43mkotsu[39;49m[33;43m"[39;49m[43m)[49m
[32m     86[39m     [38;5;28;01mimport[39;00m[38;5;250m [39m[34;01mkotsu[39;00m
[32m     88[39m     [38;5;28;01mfrom[39;00m[38;5;250m [39m[34;01msktime[39;00m[34;01m.[39;00m[34;01mbenchmarking[39;00m[34;01m.[39;00m[34;01m_base_kotsu[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m (
[32m     89[39m         SktimeModelRegistry,
[32m     90[39m         SktimeValidationRegistry,
[32m     91[39m     )

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\sktime\utils\validation\_dependencies.py:163[39m, in [36m_check_soft_dependencies[39m[34m(package_import_alias, severity, obj, msg, suppress_import_stdout, *packages)[39m
[32m    159[39m [38;5;66;03m# if msg is not None, none of the above is executed,[39;00m
[32m    160[39m [38;5;66;03m# so if msg is passed it overrides the default messages[39;00m
[32m    162[39m [38;5;28;01mif[39;00m severity == [33m"[39m[33merror[39m[33m"[39m:
[32m--> [39m[32m163[39m     [38;5;28;01mraise[39;00m [38;5;167;01mModuleNotFoundError[39;00m(msg) [38;5;28;01mfrom[39;00m[38;5;250m [39m[34;01me[39;00m
[32m    164[39m [38;5;28;01melif[39;00m severity == [33m"[39m[33mwarning[39m[33m"[39m:
[32m    165[39m     warnings.warn(msg, stacklevel=[32m2[39m)

[31mModuleNotFoundError[39m: No module named 'kotsu'. 'kotsu' is a soft dependency and not included in the base sktime installation. Please run: `pip install kotsu` to install the kotsu package. To install all soft dependencies, run: `pip install sktime[all_extras]`

